In [1]:
import time
start = time.time()
print("time :", time.time() - start)

time : 5.507469177246094e-05


# 내 답안

In [11]:
def solution(array, commands):
    answer = []
    for command in commands:
        [i, j, k] = command
        answer.append(sorted(array[i-1:j])[k-1])
    return answer

In [12]:
solution([1, 5, 2, 6, 3, 7, 4], [[2, 5, 3], [4, 4, 1], [1, 7, 3]])

2 5 3
[2, 3, 5, 6]
4 4 1
[6]
1 7 3
[1, 2, 3, 4, 5, 6, 7]


[5, 6, 3]

In [73]:
def solution(n, computers):
    """ 네트워크가 뭔지 아직 모르겠음. 그냥 예제에 따라 적절한 리턴값을 뽑도록 함수를 짜고자 함."""
    answer = n
    
    j_list = []
    for k in range(n-1):  # 검사해야할 j값을 찾는 루프
        [j_list.append(i) for i in range(1+k,n)]

    i_list = []
    for h in range(n-1):  # 검사해야할 i값을 찾는 루프
        i_list += [0+h]*(n-1-h)
    
    # i, j 를 한번에 사용할 수 있도록 튜플로 묶어줌
    ij_list = list(zip(i_list, j_list))
    
    print(ij_list)
    dic = {}
    # 여기에 해당되면 연결되어있는것.
    for (i, j) in ij_list:
        print(i, j)
        if computers[i][j]==1:
            answer -= 1
            dic[f"{i}{j}"] = True
        else:
            dic[f"{i}{j}"] = False
    print(dic)
    return answer

In [74]:
solution(3, [[1, 1, 0], [1, 1, 0], [0, 0, 1]])

[(0, 1), (0, 2), (1, 2)]
0 1
0 2
1 2
{'01': True, '02': False, '12': False}


2

In [77]:
print(solution(4, [[1, 1, 0, 1], [1, 1, 0, 0], [0, 0, 1, 1], [1, 0, 1, 1]]),1)

[(0, 1), (0, 2), (0, 3), (1, 2), (1, 3), (2, 3)]
0 1
0 2
0 3
1 2
1 3
2 3
{'01': True, '02': False, '03': True, '12': False, '13': False, '23': True}
1 1


In [76]:
print(solution(4, [[1, 0, 0, 0], [0, 1, 0, 0], [0, 0, 1, 0], [0, 0, 0, 1]]), 4)

[(0, 1), (0, 2), (0, 3), (1, 2), (1, 3), (2, 3)]
0 1
0 2
0 3
1 2
1 3
2 3
{'01': False, '02': False, '03': False, '12': False, '13': False, '23': False}
4 4


In [72]:
0,1  0,2  1,2

SyntaxError: invalid syntax (635441761.py, line 1)

In [27]:
l = []
l.append(0)
l

[0]

In [29]:
[0]*3+[1]*2

[0, 0, 0, 1, 1]

In [ ]:
i_list = [0+k]*(n-k) for k in range(n-1)

In [88]:
code = "abcdefghijklmnopqrstuvwxyz"
message = "test"

dictionary_s = {}
dictionary_d = {}
numbers = []
for i  in range(1, 27):
    numbers.append('%02d' % (i))
# print(numbers)

# code는 무조건 26개. 바로 매치 가능. num도 26개이므로.
for i, num in enumerate(numbers):
    dictionary_s[code[i]] = num
    dictionary_d[num] = code[i]
print(dictionary_s)
print(dictionary_d)

{'a': '01', 'b': '02', 'c': '03', 'd': '04', 'e': '05', 'f': '06', 'g': '07', 'h': '08', 'i': '09', 'j': '10', 'k': '11', 'l': '12', 'm': '13', 'n': '14', 'o': '15', 'p': '16', 'q': '17', 'r': '18', 's': '19', 't': '20', 'u': '21', 'v': '22', 'w': '23', 'x': '24', 'y': '25', 'z': '26'}
{'01': 'a', '02': 'b', '03': 'c', '04': 'd', '05': 'e', '06': 'f', '07': 'g', '08': 'h', '09': 'i', '10': 'j', '11': 'k', '12': 'l', '13': 'm', '14': 'n', '15': 'o', '16': 'p', '17': 'q', '18': 'r', '19': 's', '20': 't', '21': 'u', '22': 'v', '23': 'w', '24': 'x', '25': 'y', '26': 'z'}


In [93]:
answer = ''.join(dictionary_s[m] for m in message)
print(answer)

20051920


In [108]:
message = 'ageg'
answer = ''
try:
    int(message) # 오류나면 문자, 오류 안나면 숫자
    # 숫자임 - 2개씩 읽기
    decimal_message = [''.join([message[i],message[i+1]]) for i in range(0,len(message),2)]
    answer = ''.join(dictionary_d[m] for m in decimal_message)
    
except:
    # 문자임
    answer = ''.join(dictionary_s[m] for m in message)
print(answer)

01070507


In [113]:
#핵심 소스코드의 설명을 주석으로 작성하면 평가에 큰 도움이 됩니다.
class Solution:
    def solution(self, code, message):
        # 숫자 26개 포매팅 (문자열로 처리하면 됨)
        dictionary_s = {}
        dictionary_d = {}
        numbers = []
        for i  in range(1, 27):
            numbers.append('%02d' % (i))
        
        
        # code 문자를 숫자에 매치시키기(딕셔너리로 만들어두기)
        for i, num in enumerate(numbers):
            dictionary_s[code[i]] = num
            dictionary_d[num] = code[i]
        
        # message가 문자이면 각 문자에 대응하는 숫자를 가져오기 
        try:
            int(message) # 오류나면 문자, 오류 안나면 숫자
            # 숫자임 - 2개씩 읽기
            decimal_message = [''.join([message[i],message[i+1]]) for i in range(0,len(message),2)]
            answer = ''.join(dictionary_d[m] for m in decimal_message)

        except:
            # 문자임
            answer = ''.join(dictionary_s[m] for m in message)
        
        
        # message가 숫자(str)이면 이 숫자에 대응하는 문자를 가져오기
        return answer

In [114]:
code = "abcdefghijklmnopqrstuvwxyz"
message = "test"
s = Solution()
s.solution(code, message)

'20051920'

In [115]:
code = "abcdefghijklmnopqrstuvwxyz"
message = "20051920"
s = Solution()
s.solution(code, message)

'test'

In [127]:
answer = 0
answer -= 180
print(answer)

-180


In [219]:
#핵심 소스코드의 설명을 주석으로 작성하면 평가에 큰 도움이 됩니다.
class Solution:
    def solution(self, instructions):
        answer = 0
        
        # 1 -- 첫번째 "HALT" 를 찾아서 그 다음 명령은 모두 배제함.
        if "HALT" in instructions:
            i_halt = instructions.index("HALT")
            commands = instructions[:i_halt]
        else:
            commands = instructions
        
        # 지울 명령을 임시로 담아둔다. 바로 지우면 for문 멈춤
        commands_temp = []
        
        # 2 -- 앞의 명령들로 각도를 계산. 명령을 숫자로 대응시킴.
        for command in commands:
            if command == "LEFT":
                answer -= 90
                commands_temp.append("LEFT")
                
            elif command == "RIGHT":
                answer += 90
                commands_temp.append("RIGHT")
                
            elif command == "TURN AROUND":
                answer += 180
                commands_temp.append("TURN AROUND")
            else:
                print("error", command)
        
        # 지우기
        [commands.remove(temp) for temp in commands_temp]

        # 3 -- 여기부턴 모든 명령이 "방향 숫자"이므로 split해서 숫자만큼 answer에 더하기
        for com in commands:
            direction = com.split(" ")[0]
            degree = int(com.split(" ")[1])
            if direction == "LEFT":
                answer -= degree
            elif direction == "RIGHT":
                answer += degree
            else:
                print("error", com)
        
        # 4 -- 각도 구하기
        if answer<0:
            answer = 360-(abs(answer)%360)
        elif answer>=0:
            answer = (answer%360)
        
        if answer == 360:
            answer = 0
        
        return answer

In [220]:
instructions = ["RIGHT", "LEFT 70", "RIGHT", "LEFT", "LEFT 90", "HALT", "RIGHT", "HALT"]
s = Solution()
s.solution(instructions)

error LEFT 70
error LEFT 90


290

In [217]:
360-abs(-360)%360

360

In [228]:
#핵심 소스코드의 설명을 주석으로 작성하면 평가에 큰 도움이 됩니다.
class Solution:
    def solution(self, candles):
        # 전략 1)
        #   정렬 -> 앞1개-1 -> 정렬 -> 앞2개 -1 ...
        # 최대 일수: len(candles) 인데 최대값<len(candles) 이면 최대 일수 = 최대값
        # 0이 있으면 멈춤
        for i in range(1, len(candles)):
            print(i)
            candles = sorted(candles)[:i] - [1]*i
            if 0 in candles:
                answer = i
                break
        
        return answer

In [229]:
candles = [2,2,2,4]
print(sorted(candles)[:1])
s = Solution()
s.solution(candles)

[2]
1


TypeError: unsupported operand type(s) for -: 'list' and 'list'

In [ ]:
candles.sort() = [1]*i

In [237]:
import numpy as np
ar_candles = np.array(candles)
ar_candles - np.array([1]*4)

array([1, 1, 1, 3])

In [265]:
np.sort(ar_candles)[::-1] - np.array([1]*4)

array([3, 1, 1, 1])

In [254]:
ar_candles

array([2, 2, 2, 4])

In [304]:
candles

[2, 2, 2, 4]

In [309]:
#핵심 소스코드의 설명을 주석으로 작성하면 평가에 큰 도움이 됩니다.
import numpy as np

class Solution:
    def solution(self, candles):
        # 전략 1)
        #   정렬 -> 앞1개-1 -> 정렬 -> 앞2개 -1 ...
        # 최대 일수: len(candles) 인데 최대값<len(candles) 이면 최대 일수 = 최대값
        # 0이 있으면 멈춤
        answer = 0
        for i in range(1, len(candles)+1):
            print(i)
            ar_candles = np.array(sorted(candles, reverse=True)[:i])
            print(ar_candles)
            ar_candles = np.sort(ar_candles)[::-1] - np.array([1]*i)

            candles = sorted(candles, reverse=True)
            candles[:i] = ar_candles.tolist()

            print(candles)

            if 0 in candles:
                answer = i
                break
        else:
            answer = i
        return answer

In [310]:
candles = [2,2,2,4]
s = Solution()
s.solution(candles)

1
[4]
[3, 2, 2, 2]
2
[3 2]
[2, 1, 2, 2]
3
[2 2 2]
[1, 1, 1, 1]
4
[1 1 1 1]
[0, 0, 0, 0]


4

In [312]:
candles = [1,2,3,4,5,6]
s = Solution()
s.solution(candles)

1
[6]
[5, 5, 4, 3, 2, 1]
2
[5 5]
[4, 4, 4, 3, 2, 1]
3
[4 4 4]
[3, 3, 3, 3, 2, 1]
4
[3 3 3 3]
[2, 2, 2, 2, 2, 1]
5
[2 2 2 2 2]
[1, 1, 1, 1, 1, 1]
6
[1 1 1 1 1 1]
[0, 0, 0, 0, 0, 0]


6

# 모범답안